#ifndef __ERRORS_H__
#define __ERRORS_H__

#define INPUT_ERROR 2
#define TOO_LONG_STR_ERROR 3
#define INVALID_CHARACTERS_ERROR 4
#define NOT_ENOUGH_MATHS_SIGNS_ERROR 5
#define INCORRECT_E_LETTER_AMOUNT_ERROR 6
#define INCORRECT_POINTS_AMOUNT_ERROR 7
#define INCORRECT_POINT_PLACE_ERROR 8
#define WRONG_FORMAT_ERROR 9
#define INCORRECT_MANTISSA_LEN_ERROR 10
#define INCORRECT_POWER_LEN_ERROR 11
#define ZERO_DIVISION_ERROR 12
#define POWER_OVERFLOW_ERROR 13
#define EMPTY_STRING_ERROR 14

#endif // __ERRORS_H__